#!/usr/bin/env bash

wget https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-common_5.7.25-1ubuntu18.10_amd64.deb

sudo dpkg -i mysql-common_5.7.25-1ubuntu18.10_amd64.deb



wget https://downloads.mysql.com/archives/get/p/23/file/mysql-community-client_5.7.25-1ubuntu18.10_amd64.deb

sudo dpkg -i mysql-community-client_5.7.25-1ubuntu18.10_amd64.deb


wget https://downloads.mysql.com/archives/get/p/23/file/mysql-client_5.7.25-1ubuntu18.10_amd64.deb

sudo dpkg -i mysql-client_5.7.25-1ubuntu18.10_amd64.deb


wget https://downloads.mysql.com/archives/get/p/23/file/libmysqlclient20_5.7.25-1ubuntu18.10_amd64.deb

sudo dpkg -i libmysqlclient20_5.7.25-1ubuntu18.10_amd64.deb


sudo apt install libmecab2



wget https://cdn.mysql.com/archives/mysql-5.7/mysql-community-server_5.7.25-1ubuntu18.10_amd64.deb

sudo dpkg -i mysql-community-server_5.7.25-1ubuntu18.10_amd64.deb
