#!/usr/bin/env bash
# minimum number of commands used to automate the fix.
# Configure nginx to listen on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart

