#!/usr/bin/env bash
# Use a while loop, if,elif and else statement to write script


i=1

while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best school"
	fi
	i=$((i+1))
done
